// Module included in the following assemblies:
//
//  * serverless/event_workflows/serverless-subs.adoc

[id="serverless-creating-subscriptions-kn_{context}"]
= Creating subscriptions using the Knative CLI

You can create a subscription to connect a channel to a sink by using the `kn` CLI.

.Prerequisites

To create subscriptions using the `kn` CLI, ensure that:

* The {ServerlessOperatorName} and Knative Eventing are installed on your {product-title} cluster.
* You have installed the `kn` CLI.
* You have created a project or have access to a project with the appropriate roles and permissions to create applications and other workloads in {product-title}.

.Procedure

* Create a subscription to connect a sink to a channel:
+
[source,terminal]
----
$ kn subscription create <subscription_name> \
  --channel <Group:Version:Kind>:<channel_name> \ <1>
  --sink <sink_prefix>:<sink_name> \ <2>
  --sink-reply <sink_prefix>:<sink_name> \ <3>
  --sink-dead-letter <sink_prefix>:<sink_name> <3>
----
<1> `--channel` specifies the source for cloud events that should be processed. You must provide the channel name. If you are not using the default channel that is backed by the Channel resource, you must prefix the channel name with the `<Group:Version:Kind>` for the specified channel type. For example, this will be `messaging.knative.dev:v1beta1:KafkaChannel` for a Kafka backed channel.
<2> `--sink` specifies the target destination to which the event should be delivered. By default, the `<sink_name>`` is interpreted as a Knative service of this name, in the same namespace as the subscription. You can specify the type of the sink by using one of the following prefixes:
`ksvc`:: A Knative service.
`svc`:: A Kubernetes Service.
`channel`:: A channel that should be used as destination. Only default channel types can be referenced here.
`broker`:: An Eventing broker.
<3> `--sink-reply` and `--sink-dead-letter` are optional arguments. They can be used to specify where the sink reply will be sent to, and where to send the cloud event in case of a failure, respectively. Both use the same naming conventions for specifying the sink as the `--sink` flag.
+
.Example command
[source,terminal]
----
$ kn subscription create mysubscription --channel mychannel --sink ksvc:event-display
----
+
.Example output
[source,terminal]
----
Subscription 'mysubscription' created in namespace 'default'.
----

.Verification

* To confirm that the channel is connected to the event sink, or _subscriber_, by a subscription, list the existing subscriptions and inspect the output:
+
[source,terminal]
----
$ kn subscription list
----
+
.Example output
[source,terminal]
----
NAME            CHANNEL             SUBSCRIBER           REPLY   DEAD LETTER SINK   READY   REASON
mysubscription   Channel:mychannel   ksvc:event-display                              True
----
