// Module included in the following assemblies:
//
// * networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc

:_mod-docs-content-type: REFERENCE
[id="virt-example-ethernet-nncp_{context}"]
= Example: Ethernet interface node network configuration policy

[role="_abstract"]
You can configure an Ethernet interface on nodes in the cluster by applying a `NodeNetworkConfigurationPolicy` manifest to the cluster.

The following YAML file is an example of a manifest for an Ethernet interface.
It includes sample values that you must replace with your own information.

[source,yaml]
----
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: eth1-policy
spec:
  nodeSelector:
    kubernetes.io/hostname: <node01>
  desiredState:
    interfaces:
    - name: eth1
      description: Configuring eth1 on node01
      type: ethernet
      state: up
      ipv4:
        dhcp: true
        enabled: true
----
+
where:
+
`name` (under `metadata`):: Specifies the name of the policy.
`nodeSelector`:: Optional: If you do not include the `nodeSelector` parameter, the policy applies to all nodes in the cluster.
`kubernetes.io/hostname`:: Specifies a hostname node selector.
`name` (under `interfaces`):: Specifies the name of the interface.
`description`:: Optional: Specifies a human-readable description of the interface.
`type`:: Specifies the type of interface. This example creates an Ethernet networking interface.
`state`:: Specifies the requested state for the interface after creation.
`dhcp`:: Optional: If you do not use `dhcp`, you can either set a static IP or leave the interface without an IP address.
`enabled`:: Specifies that `ipv4` is enabled in this example.
